python3-cuda: Add missing upstream status to patch
OE-core/master has QA diagnostics about it and some distros e.g. yoe
turn that into an Error

Fixes
ERROR: python3-cuda-12.2.1-r0 do_patch: QA Issue: Missing Upstream-Status in patch

Signed-off-by: Khem Raj <raj.khem@gmail.com>