deepstream-6.3: PACKAGECONFIG updates
* Added 'nmos' PACKAGECONFIG setting for enabling/disabling
  inclusion of NMOS (Network Media Open Specification) support,
  which requires avahi to be built with libdns_sd in its
  PACKAGECONFIG.
* Added dependency for the 'azure' PACKAGECONFIG setting on
  azure-iot-sdk

This is a backport of https://github.com/OE4T/meta-tegra-community/commit/79dea834cd0a04c7fd6399f8394905d759e707ce
to deepstream 6.3

Resolves build error:
```
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/libnss_mdns.so.2 conflicts between attempted installs of libnss-mdns-0.15.1-r0.armv8a_tegra and mdns-2200.100.94.0.2-r0.armv8a_tegra
```

Signed-off-by: Ilies CHERGUI <ichergui@nvidia.com>
Signed-off-by: Matt Madison <matt@madison.systems>
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>